# Generated by Django 4.2.17 on 2024-12-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JokeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_input', models.TextField()),
                ('text_joke', models.TextField()),
            ],
        ),
    ]
